version: '3.4'
services:
  certbot:
    build: .
    image: sba-certificate-renewal
    environment:
    - CERT_BUCKET_NAME=my-bucket-to-store-certs
    - CERT_BUCKET_PATH=/my/path/to/the/certs/
    - CERT_HOSTNAME=hostname.to.register.example.org
    #- AWS_PROFILE=my-nondefault-profile
    #- DRY_RUN=true
    #volumes:
    #- "~/.aws:/root/.aws"
