version: '3.4'
services:
  certbot:
    build: .
    image: sba-certificate-renewal
    environment:
    #- AWS_PROFILE=hz-lower
    #- CERT_BUCKET_NAME=my-bucket-with-the-certs
    #- CERT_BUCKET_PATH=/my/path/to/the/certs/
    #- CERT_HOSTNAME=hostname.to.register
    #- DRY_RUN=true
    #volumes:
    #- "~/.aws:/root/.aws"
