version: 2
workflows:
  version: 2
  test:
    jobs:
      - poirot
jobs:
  poirot:
    docker:
       - image: ussba/cc-python:3
         environment:
           FOO: foo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            poirot --patterns poirot-patterns.txt
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
